### ISSUE TITLE
the result is not recorded

### ISSUE THREAD

**Issue by Lubard** [itmammoth/rails_sortable#1]
`	<% @staffs = Staff.order(:staff_order) %>
	<table>
	<tbody class="sortable">  
	    <% sortable_fetch(@staffs) do |staff, id_tag| %>  
	      <tr id="<%= id_tag %>">
	        <td><%= staff.nickname %></td>
	        <td><%= staff.staff_order %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>`

here's my code, and when I drag & drop the staff and flush, nothing changed...

sort changed:
![screen shot 2017-04-10 at 1 00 16 pm](https://cloud.githubusercontent.com/assets/4156201/24844411/be9a54cc-1ded-11e7-83f1-61f3411cd605.png)
Then Flush:

![screen shot 2017-04-10 at 1 00 38 pm](https://cloud.githubusercontent.com/assets/4156201/24844412/bed5999c-1ded-11e7-81a1-cf5531f974a0.png)

is there anything I missed?

**Comment by itmammoth** [comment]
@Lubard Let me have a look at your model and javascript.

**Comment by Lubard** [comment]
@itmammoth 
Hi!
The model as:
`class Staff < ActiveRecord::Base
	include RailsSortable::Model

	has_many :customers
	has_many :orders

	has_many :staff_time_periods
	has_one :default_average_period
	has_one :default_start_date

	# validates :email, unique: true

	has_secure_password
	set_sortable :staff_order`
and the page is like:
`<div align="center" style="margin-top: 50px;">
	<% @staffs = Staff.active_sales_staff.order(:staff_order) %>
	<table>
	<tbody class="sortable">  
	    <% sortable_fetch(@staffs) do |staff, id_tag| %>  
	      <tr id="<%= id_tag %>">
	        <td><%= staff.nickname %></td>
	        <td><%= staff.staff_order %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

<script>
  $(".sortable").railsSortable();
</script>
`
  $(".sortable").railsSortable(); is the one and only js code in this page

**Comment by itmammoth** [comment]
@Lubard 
I found a bug in `set_sortable` method, and which has been fixed.
Please try it again with the gem version `0.0.5`.
Thx

**Comment by Lubard** [comment]
Hi @itmammoth 
Sorry for the missing for last couple days...
I tried both version 0.1.0 and 0.1.1, they were both failed to fix this :(

**Comment by itmammoth** [comment]
@Lubard 
Any errors in the browser or the server console?

**Comment by Lubard** [comment]
@itmammoth 
Oh!
I just found one:

[Error] Failed to load resource: the server responded with a status of 422 (Unprocessable Entity) (reorder, line 0)

after I dragged the item.

` 
def parse_params
    klass_name = params.keys.first
    ids = params[klass_name].map {|id| id.to_i }
    [ klass_name.constantize, ids ]
  end
`
undefined method `map' for "sortable":String for line 20 > <

**Comment by itmammoth** [comment]
Can you push your app to Github?

**Comment by kramersharp** [comment]
I also get the 422 error, and the logs say "ActiveRecord::RecordInvalid - Validation failed: Name has already been taken"

**Comment by itmammoth** [comment]
@kramersharp 
I think you have a duplicated `name` value in your model, and which causes the validation error.

**Comment by seanfcarroll** [comment]
Closable?

**Comment by itmammoth** [comment]
Yeah, the bug has been fixed.
I'll close this issue in a moment.
