### ISSUE TITLE
Use rails_sortable for multiple classes

### ISSUE THREAD

**Issue by varg90** [itmammoth/rails_sortable#19]
Hi there! 
Is it possible to use this gem if I need to sort items that have different class / stored in different tables in the db? Both have `sort` attribute. For example:
`<% (first_items + second_items).each_with_sortable_id  do |item, sortable_id| %>`
The problem is that it stores the same `sort` value in the db for each of the models independently

Thanks

**Comment by itmammoth** [comment]
Unfortunately, rails_sortable now does not support multiple classes sorting.
But it seems useful in some case, so I will make it sometime.

**Comment by itmammoth** [comment]
Please see the example.
https://github.com/itmammoth/rails_sortable/wiki/Multiple-classes
