### ISSUE TITLE
Asset pipeline error using uglifier

### ISSUE THREAD

**Issue by robban** [itmammoth/rails_sortable#26]
When deploying to heroku, I got an error when rake assets:precompile ran: 

> ExecJS::RuntimeError: SyntaxError: Invalid assignment
> JS_Parse_Error.Object.defineProperty.get((execjs):3538:621)

I managed to solve this by replacing 

> config.assets.js_compressor = :uglifier

with

> config.assets.js_compressor = Uglifier.new(harmony: true)

Is there some ES6 code in rails_sortable that makes uglifier fail without the harmony setting?

**Comment by itmammoth** [comment]
Oh, sorry.
I didn't know `Destructuring assignment` is a part of ES6.
- https://github.com/itmammoth/rails_sortable/blob/master/vendor/assets/javascripts/plugin.js#L30
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

I will fix it later.
Thank you.

**Comment by itmammoth** [comment]
rails_sortable-1.2.1 was pushed to rubygems.
