### ISSUE TITLE
Default axis

### ISSUE THREAD

**Issue by sebastienwozny** [itmammoth/rails_sortable#36]
Hi @itmammoth and thanks for the gem!
Why have you specified the default axis "y" in your gem ?

It make more sens to me to keep the widget default parameter. (Made me crazy for twenty minutes before I understand)

https://github.com/itmammoth/rails_sortable/blob/b4b273ba72d05d96a76a4bc1d5e9f2e6ce895ef3/vendor/assets/javascripts/plugin.js#L6

https://api.jqueryui.com/sortable/#option-axis
```
axis 
Type: String
Default: false
```

xoxo

**Comment by itmammoth** [comment]
Thanks @sebastienwozny 
You have a point.
The default parameters should have been more respected.
I will make a change to it later.
